### ISSUE TITLE
Domanda

### ISSUE THREAD

**Issue by Victini378** [pymike00/youtube-scripts#1]
Buongiorno! Vorrei chiedere ma il codice è protetto da una licenza?
E perchè non fare repo diversi per ogni tipologia di codice avendo così la possibilità di poter fare il fork di un singolo codice?

**Comment by pymike00** [comment]
Ciao! Ho appena aggiunto licenza MIT ;)

Per quanto riguarda la seconda domanda, sai che ci ho pensato su un bel pò prima di fare questa scelta? Capisco però la tua osservazione, ma ho optato per questo stile in quanto trattandosi del source code dei tutorial, gran parte dei file contengono poche righe di codice, e posso inoltre condividere un unico link dal sito e dai vari canali social. 

Happy Coding!

**Comment by Victini378** [comment]
Grazie mille!!! Buona giornata e buona programmazione!!!

**Comment by pymike00** [comment]
A presto! :+1:
